# Generated by Django 3.2 on 2022-07-19 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso_titulo', models.CharField(max_length=255)),
                ('curso_contenido', models.TextField()),
                ('curso_publicado', models.DateTimeField(verbose_name='Fecha de Publicación')),
            ],
        ),
    ]
